### ISSUE TITLE
Cannot use default build.bat

### ISSUE THREAD

**Issue by RafPe** [funnelweblog/FunnelWeb#56]
Hey ,

I was trying to run the latest build.bat to get stable build however I get the following errors : 

C:\Users\Rafal\Downloads\FunnelWeb-master\FunnelWeb-master\src\FunnelWeb.Web\FunnelWeb.Web.csproj(535,3): error MSB4019: The imported project "C:\Program Files
mport> declaration is correct, and that the file exists on disk.
  Successfully installed 'Autofac 2.4.2.696'.
  Successfully installed 'Autofac 2.6.3.862'.
  Successfully installed 'dbup 2.0.113'.
  Successfully installed 'dbup-sqlce 2.0.113'.
  Successfully installed 'FluentNHibernate 1.3.0.733'.
  Successfully installed 'Iesi.Collections 3.3.2.4000'.
  Successfully installed 'Microsoft.AspNet.Mvc 4.0.20710.0'.
  Successfully installed 'Microsoft.AspNet.Razor 2.0.20710.0'.
  Successfully installed 'Microsoft.AspNet.WebPages 2.0.20710.0'.
  Successfully installed 'Microsoft.SqlServer.Compact 4.0.8876.1'.
  Successfully installed 'Microsoft.Web.Infrastructure 1.0.0.0'.
  Successfully installed 'NHibernate 3.3.2.4000'.
  Successfully installed 'NSubstitute 1.4.3.0'.
  Successfully installed 'SqlServerCompact 4.0.8854.1'.
C:\Users\Rafal\Downloads\FunnelWeb-master\FunnelWeb-master\src\FunnelWeb.Web\FunnelWeb.Web.csproj(535,3): error MSB4019: The imported project "C:\Program Files
mport> declaration is correct, and that the file exists on disk.
  Successfully installed 'Autofac.Mvc3 2.6.3.862'.
  Successfully installed 'blogml 2.2.0'.
  Successfully installed 'Microsoft.WindowsAzure.ConfigurationManager 1.7.0.3'.
  Successfully installed 'MiniProfiler 2.0.2'.
  Successfully installed 'NHibernate.Validator 1.3.2.4000'.
  Successfully installed 'SharpZipLib 0.86.0'.
  Successfully installed 'WindowsAzure.Storage 1.7.0.0'.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly
eck to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\Rafal\Downloads\FunnelWeb-ma
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly
sembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\Rafal\Downloads\FunnelWeb-master\FunnelWeb-master\s
Authentication\Internal\SqlFunnelWebMembership.cs(4,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you mi
Authentication\Internal\SqlAuthenticator.cs(3,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you missing
Filters\FunnelWebRequestAttribute.cs(3,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you missing an asse
Filters\FunnelWebRequestAttribute.cs(9,46): error CS0246: The type or namespace name 'ActionFilterAttribute' could not be found (are you missing a using directi
Providers\File\AzureBlobFileRepository.cs(5,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you missing an
Providers\File\FileRepository.cs(6,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you missing an assembly
Providers\File\FileRepositoryBase.cs(3,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you missing an asse
Providers\File\IFileRepository.cs(2,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you missing an assembl
Model\EntryRevision.cs(7,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you missing an assembly reference
RoutableFunnelWebExtension.cs(2,18): error CS0234: The type or namespace name 'Mvc' does not exist in the namespace 'System.Web' (are you missing an assembly re
Filters\FunnelWebRequestAttribute.cs(23,48): error CS0246: The type or namespace name 'ActionExecutingContext' could not be found (are you missing a using direc
Filters\FunnelWebRequestAttribute.cs(29,47): error CS0246: The type or namespace name 'ResultExecutedContext' could not be found (are you missing a using direct
Providers\File\AzureBlobFileRepository.cs(218,25): error CS0246: The type or namespace name 'ActionResult' could not be found (are you missing a using directive
Providers\File\FileRepository.cs(145,25): error CS0246: The type or namespace name 'ActionResult' could not be found (are you missing a using directive or an as
Providers\File\FileRepositoryBase.cs(34,25): error CS0246: The type or namespace name 'ActionResult' could not be found (are you missing a using directive or an
Providers\File\IFileRepository.cs(17,9): error CS0246: The type or namespace name 'ActionResult' could not be found (are you missing a using directive or an ass
Model\EntryRevision.cs(49,10): error CS0246: The type or namespace name 'AllowHtml' could not be found (are you missing a using directive or an assembly referen
Model\EntryRevision.cs(49,10): error CS0246: The type or namespace name 'AllowHtmlAttribute' could not be found (are you missing a using directive or an assembl

Can anyone point to some direction how to get this build ?

**Comment by JakeGinnivan** [comment]
MVC used to be installed in the GAC. The references to MVC need to be deleted and the MVC NuGet packages need to be installed. Pull request welcome :)

**Comment by RafPe** [comment]
Hey ,

As it might help others :) I had to change paths in the build file to include VS version 12 and use hard coded paths instead of variables and then it have build successfully.

**Comment by JakeGinnivan** [comment]
Could you submit a pull request? :)

**Comment by RafPe** [comment]
As stupid it may sound :) is there a "RTM how to do that" link for ppl like me  ?

**Comment by JakeGinnivan** [comment]
Not stupid at all, we all have had to make our first pull request. 

https://help.github.com/articles/using-pull-requests/ and https://help.github.com/articles/creating-a-pull-request/ are a good place to start. There are also plenty of 'how to use git' guides on the internet. It is really worth spending an hour or so trying to understand git and go through the process of making a pull request, git is being adopted all over the place and it can have a bit of a learning curve unfortunately.

If you have any specific troubles just post here and I am happy to help
